### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by SuzanaMomo** [data301-2021-summer2/project-group31-project#1]
Hello,

My name is Suzana__ and I will be giving you some feedback on your project.

Overall, the project is a good starting point, but there is some work that needs to be done to elevate this project to our standards so its meets our expectations. 

I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1
Good Job.
## Task 2
Good job.
- [x] try to have some sort of indicator for separate tasks so that it is easier for me to identify individual tasks 
## Task 3
- [x] Your plots need to be more clear, i.e with proper legends, explanation.
## Task 4
- [x] Organize your tasks. Each research question (statement) then their plots (visualization) and then its explanation. Maintain this serial for every research question.
- [x] Along with the existing plots try have another type of plots that will help visualize your research questions more]
- [x] Your explanation or analysis of the research question is not sufficient, more in-depth explanation is required.

**Comment by RunningFox22** [comment]
I reorganizing my Task 1 & 2 to make it easier to follow and understand my codes on top of the current issues
